Scan and monitor examples using libgpiod
starnight/libgpiod-example pull request #1
Opened 2020-11-17 10:13 UTC by fsheikh

Summary: This patch adds a simple C example to search for a GPIO line
on a Linux platform with multiple GPIO controllers. It also adds another
c++ example using event loop to monitor a GPIO line.

2020-11-17 10:15 UTC, fsheikh commented
Hi @starnight. I really found the examples quite useful. Although one can look into ligpiod official project, they are still useful for example when one does not want to rebuilt that whole project. Just added some more examples which fitted a use-case I was working on. All in the hope that others may find them useful. Please feel free to review. Cheers!

2020-11-17 12:43 UTC, starnight reviewed
Thanks for your contribution.  However, please split the two functions/folders: libgpiod-monitor and libgpiod-scan from one commit to two commits.  Each commit for one of the function.

2020-11-17 12:43 UTC, starnight commented on libgpiod-monitor/main.cpp
> +// constants
Please transfer whole line comment from `//` to `/* ... */` for the coding style.  Include the following line comments.

2020-11-17 12:43 UTC, starnight commented on libgpiod-monitor/main.cpp
> +    while((optIn = getopt(argc, argv, "uhn:l:")) != EOF) {
I did not know `getopt()` before.  I learned this is useful function!  Cool!  Thanks :)

2020-11-20 16:59 UTC, fsheikh commented
@starnight please feel free to have another look!

2024-01-29 10:13 UTC, starnight requested changes
After 4 years, I just learned I did not submit the review request.

2024-01-29 10:13 UTC, starnight commented on libgpiod-monitor/main.cpp
> +    std::cout << "     -l    : Line number to search in GPIO controllersi, Default 0" << std::endl;
Is "controllersi" typo?

2024-01-29 10:13 UTC, starnight commented on libgpiod-scan/main.c
> +    printf("     -l    : Line number to search in GPIO controllersi, Default 0 \n");
Is "controllersi" typo?

2024-01-29 10:13 UTC, starnight commented on libgpiod-scan/main.c
> +    // Boilerplate command line arguments processing
Please use the comment as /* ... */ here.

2024-01-29 10:13 UTC, starnight commented on libgpiod-scan/main.c
> +        printf("getopt loop running\n");
Is here any special idea to put this `printf`?

2024-02-04 14:13 UTC, fsheikh commented on libgpiod-monitor/main.cpp
> +    std::cout << "     -l    : Line number to search in GPIO controllersi, Default 0" << std::endl;
Done!

2024-02-04 14:13 UTC, fsheikh commented on libgpiod-scan/main.c
> +    printf("     -l    : Line number to search in GPIO controllersi, Default 0 \n");
Done!

2024-02-04 14:13 UTC, fsheikh commented on libgpiod-scan/main.c
> +    // Boilerplate command line arguments processing
Done!

2024-02-04 14:14 UTC, fsheikh commented on libgpiod-scan/main.c
> +        printf("getopt loop running\n");
No good reason, possibly left-over from a debug-cycle, removed!

2024-02-04 14:14 UTC, fsheikh commented
> After 4 years, I just learned I did not submit the review request.

Perhaps it is never too late :smile:

2024-02-14 04:03 UTC, starnight commented
Squashed the fix into the previous commits and pushed to master.  Thanks

2024-02-14 04:03 UTC, closed without merging